version: 2

models:
  - name: dim_properties_sql
    description: Dimensions of properties, written in SQL.
    columns:
      - name: property_id
        description: The primary key for properties.
        tests:
          - unique
          - not_null

  - name: dim_properties_py
    description: Dimensions of properties, written in Python.
    config:
      materialized: table
      tags: ['python']
    columns:
      - name: property_id
        description: The primary key for properties.
        tests:
          - unique
          - not_null

exposures:

  - name: weekly_property_management_metrics
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?

    depends_on:
      - ref('fct_leases')
      - ref('dim_properties_py')
      - ref('dim_properties_sql')
      - source('property_management', 'units')

    owner:
      name: Eddo from Metadata
      email: eddo.hintoso@dbtlabs.com
